### ISSUE TITLE
突然变乌龟了 求助

### ISSUE THREAD

**Issue by sinlolicon** [a26214311/poi-plugin-achievement#6]
TypeError: Cannot read property 'length' of null
at Object.acquireContext (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:10475:20)
at new Chart.Controller (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:3891:26)
at new Chart (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:6278:21)
at createChart (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\views/calendar.es:36:15)
at SenkaCalendar.createChart [as componentDidMount] (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\views/calendar.es:131:5)
at ai (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:219:412)
at Vh (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:374)
at Yh (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
at Wh (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
at Ah (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
at og (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
at Object.enqueueSetState (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
at PluginWindowWrap.F.setState (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
at externalWindow.addEventListener.e (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\views\plugin-window-wrapper.js:183:14)

in SenkaCalendar
in div
in Row
in div
in PluginAchievement
in Connect(PluginAchievement)
in div
in PluginWrap
in I18n
in Translate(PluginWrap)
in div
in PluginWindowWrap
in div
in div
in t
in div
in ControlledTabArea
in Connect(ControlledTabArea)
in I18n
in Translate(Connect(ControlledTabArea))
in poi-nav-tabs
in poi-nav
in div
in poi-app
in PoiApp
in Connect(PoiApp)
in poi-main
in Poi
in Connect(Poi)
in Provider
in I18nextProvider

**Comment by hot36952** [comment]
> 卸载重装

我遇到相同的问题，卸载重装无法解决。
TypeError: Cannot read property 'length' of null
    at Object.acquireContext (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:10475:20)
    at new Chart.Controller (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:3891:26)
    at new Chart (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:6278:21)
    at createChart (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\views/calendar.es:36:15)
    at SenkaCalendar.createChart [as componentDidMount] (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\views/calendar.es:131:5)
    at Vh (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:216:198)
    at Zh (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:220:182)
    at C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:268
    at Object.exports.unstable_runWithPriority (C:\Game\POI\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:163)
    at Fi (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:203)
    at Di (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:249:383)
    at Yh (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:248:144)
    at Xh (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:245:332)
    at qf (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:86)
    at Object.enqueueSetState (C:\Game\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:130:228)
    at PluginWindowWrap.E.setState (C:\Game\POI\resources\app.asar\node_modules\react\cjs\react.production.min.js:13:224)
    at externalWindow.addEventListener.e (C:\Game\POI\resources\app.asar\views\components\tab-area\plugin-window-wrapper.js:181:14)

    in SenkaCalendar
    in div
    in Row
    in div
    in PluginAchievement
    in Connect(PluginAchievement)
    in PluginWrap
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(PluginWrap)
    in div
    in StyledComponent
    in plugin-window-wrapper__PoiAppTabpane
    in StyleSheetManager
    in PluginWindowWrap
    in div
    in StyledComponent
    in tab-area__PoiTabContainer
    in div
    in t
    in div
    in StyledComponent
    in tab-area__PoiTabsContainer
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in poi-app__PoiAppContainer
    in div
    in StyledComponent
    in poi-app__PoiAppE
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by a26214311** [comment]
发下配置文件
在%APPDATA%/poi/achieve/achieve.json
用记事本打开把里面的内容贴上来

**Comment by hot36952** [comment]
> 发下配置文件
> 在%APPDATA%/poi/achieve/achieve.json
> 用记事本打开把里面的内容贴上来

{"achieve":{"exphis":{}},"exphis":{"3":42982234},"lastmonth":2,"r1":0,"r501":0,"ranktime":"2019-01-31T13:03:59.004Z","rankuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"r1time":"2019-01-30T13:34:37.474Z","r501time":"2019-01-31T13:03:57.246Z","r1last":2335,"r501last":2494,"r1lasttime":44,"r501lasttime":60,"r5":0,"r5time":"2019-01-31T13:03:58.186Z","r5last":6860,"r5lasttime":60,"r20":0,"r20time":"2019-01-30T13:34:27.191Z","r20last":3336,"r20lasttime":44,"r5his":{},"r20his":{},"r100his":{},"r501his":{},"myhis":{},"mylastno":670,"mylastranktime":61,"mymagic":30,"tmpexp":42982234,"tmpno":3,"reviseType":1,"mysenka":0,"targetsenka":"2745","ignoreex":{},"need_load":false,"fensureexp":0,"fensurets":0,"fensuresenka":0,"tensureexp":42114289,"tensurets":"2019-01-31T05:00:01.002Z","tensureuex":["1-6","6-5"],"fensureuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"extraSenka":1,"zclearts":0,"extra2Senka":1,"z2clearts":0,"extra3Senka":2,"z3clearts":0,"checksum":756724,"senkaType":"calendar","chartType":"mon","myno":670}

**Comment by a26214311** [comment]
> > 发下配置文件
> > 在%APPDATA%/poi/achieve/achieve.json
> > 用记事本打开把里面的内容贴上来
> 
> {"achieve":{"exphis":{}},"exphis":{"3":42982234},"lastmonth":2,"r1":0,"r501":0,"ranktime":"2019-01-31T13:03:59.004Z","rankuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"r1time":"2019-01-30T13:34:37.474Z","r501time":"2019-01-31T13:03:57.246Z","r1last":2335,"r501last":2494,"r1lasttime":44,"r501lasttime":60,"r5":0,"r5time":"2019-01-31T13:03:58.186Z","r5last":6860,"r5lasttime":60,"r20":0,"r20time":"2019-01-30T13:34:27.191Z","r20last":3336,"r20lasttime":44,"r5his":{},"r20his":{},"r100his":{},"r501his":{},"myhis":{},"mylastno":670,"mylastranktime":61,"mymagic":30,"tmpexp":42982234,"tmpno":3,"reviseType":1,"mysenka":0,"targetsenka":"2745","ignoreex":{},"need_load":false,"fensureexp":0,"fensurets":0,"fensuresenka":0,"tensureexp":42114289,"tensurets":"2019-01-31T05:00:01.002Z","tensureuex":["1-6","6-5"],"fensureuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"extraSenka":1,"zclearts":0,"extra2Senka":1,"z2clearts":0,"extra3Senka":2,"z3clearts":0,"checksum":756724,"senkaType":"calendar","chartType":"mon","myno":670}

找不到什么原因，但是做了个更新可能会解决你的问题，请看下

**Comment by hot36952** [comment]
> > > 发下配置文件
> > > 在%APPDATA%/poi/achieve/achieve.json
> > > 用记事本打开把里面的内容贴上来
> > 
> > 
> > {"achieve":{"exphis":{}},"exphis":{"3":42982234},"lastmonth":2,"r1":0,"r501":0,"ranktime":"2019-01-31T13:03:59.004Z","rankuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"r1time":"2019-01-30T13:34:37.474Z","r501time":"2019-01-31T13:03:57.246Z","r1last":2335,"r501last":2494,"r1lasttime":44,"r501lasttime":60,"r5":0,"r5time":"2019-01-31T13:03:58.186Z","r5last":6860,"r5lasttime":60,"r20":0,"r20time":"2019-01-30T13:34:27.191Z","r20last":3336,"r20lasttime":44,"r5his":{},"r20his":{},"r100his":{},"r501his":{},"myhis":{},"mylastno":670,"mylastranktime":61,"mymagic":30,"tmpexp":42982234,"tmpno":3,"reviseType":1,"mysenka":0,"targetsenka":"2745","ignoreex":{},"need_load":false,"fensureexp":0,"fensurets":0,"fensuresenka":0,"tensureexp":42114289,"tensurets":"2019-01-31T05:00:01.002Z","tensureuex":["1-6","6-5"],"fensureuex":["1-5","1-6","2-5","3-5","4-5","5-5","6-5"],"extraSenka":1,"zclearts":0,"extra2Senka":1,"z2clearts":0,"extra3Senka":2,"z3clearts":0,"checksum":756724,"senkaType":"calendar","chartType":"mon","myno":670}
> 
> 找不到什么原因，但是做了个更新可能会解决你的问题，请看下

感谢，更新后可以打开了
